
<!-- HEAD -->
<?php include 'includes/head.php'; ?>


<body>
    <!-- NAV BAR   -->
    <?php include 'includes/nav.php'; ?>

    
<!-- This is a template page we can use when we create new pages -->
<!-- DO NOT EDIT THIS FILE! -->
 <!-- FOOTER -->   
 <?php include 'includes/footer.php' ?>   
