
<!-- HEAD -->
<?php include 'includes/head.php'; ?>


<body>
    <!-- NAV BAR   -->
    <?php include 'includes/nav.php'; ?>

    
<!-- This is a template page we can use when we create new pages -->
<!-- DO NOT EDIT THIS FILE! -->
 <!-- FOOTER -->   
 <?php include 'includes/footer.php' ?>   
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>